name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    - name: Build and test (SPM)
      run: |
        xcodebuild test -scheme DynamicBottomSheet -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
