name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    - name: Build and test (SPM)
      run: |
        xcodebuild test -scheme DynamicBottomSheet -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4' -enableCodeCoverage YES

    - name: Convert coverage to lcov
      run: |
        xcrun llvm-cov export -format=lcov \
          .build/debug/DynamicBottomSheetPackageTests.xctest/Contents/MacOS/DynamicBottomSheetPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.lcov